export const getAllUsersPath = "/user/getall"
export const googleUserVerify = "/auth/google-login"
export const saveResumePath = "/resume/save"
export const getUserResumesById = "/resume?userId=replace_id"
export const getSelectedResumesById = "/resume?resumeId=replace_id"
export const deleteResumesById = "/resume/delete/replace_id"
export const createUser = "/user/create"
export const userLoginPath = "/auth/"